### ISSUE TITLE
As a user I can easily install the Composer Playground from DockerHub

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#132]
- [ ] publish the docker image
- [ ] end user documentation for how to install and run

https://hub.docker.com/r/fabriccomposer/composer-ui/

**Comment by dselman** [comment]
Duplicates #23

**Comment by dselman** [comment]
Can this be closed?

**Comment by sstone1** [comment]
@dselman no, I think we still have to change the documentation to install the new images before we can close this user story.

**Comment by bestbeforetoday** [comment]
@EdProsser is updating the doc located at https://fabric-composer.github.io/tutorials/getting-started-playground.html to refer to composer-playground rather than composer-ui, and to correct the Yaml file link. If the updated instruction run through cleanly then this issue should be complete. Fixes are being delivered as part of a pull request associated with issue #497
