### ISSUE TITLE
As a user I can import a business network archive into Composer Playground

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#137]

**Comment by EdMoffatt** [comment]
"Import from disc" and "import a sample" are bundled into the same modal, shown on screens 2-5 of the latest low-fi, available here: https://xd.adobe.com/view/a2b13e4c-a2c7-4d56-95bc-db506cb58460/

Should add a little more detail around what happens when a file is dragged in (to come in a later version - added to our To-Do List!)

**Comment by winslet** [comment]
### Flow:

Most of the hifi's for this flow can be found in #35 but the flow for uploading a file either through a drag 'n drop or selecting "browse" can be found below:

1. User selects "Import/Replace" from the left hand nav and this modal opens:

![Fabric Composer Playground Define 2 Copy 24](http://static.gitscout.com/bc592f5b1c4a95b9998302cb596417fa222eff2c295aeedb38dd36c3259fcd02.png)

--

2. User is given the option to select "browse" in which case the standard file browser appears, or if a user drags a file in they get this: 

_interaction notes: the size of the drop area increases to allow the easier dropping of files and the table of Github BN options removes itself_

![Fabric Composer Playground Define 2 Copy 35](http://static.gitscout.com/461fdb953e5f14d65a3bf6fe2a0ae3aca4351481c7b545929d42c35255055ef1.png)

--

3. With the expectation that the upload is going to take a minimal amount of time, the screen then changes to a page giving users an overview of what the .bna file includes (this is so they can decide if that BNA is the one they need or if they need to upload another one). In effect we give them a "sneak peak" of what is included in that BNA:

![Fabric Composer Playground Define 2 Copy 40](http://static.gitscout.com/1de82bcb29d151c53075d811b4f9acdefb036751c89a07ca8dfe28d69cf58a4f.png)


### Assets:

Marketch: [Composer_Playground_BNA_Upload_SW_1.zip](http://static.gitscout.com/21e7d51868b50a74b5f98ea82df0c09a2c22f22234e12b7a9cbbf59b3afae2f2.zip)

Illustrations (SVG's): [Issue_137_Illustrations_BNA_Upload.zip](http://static.gitscout.com/a553bf9273a70998163cd283710405bde72a525d35702bbc7242ce0583f11736.zip)

**Comment by caroline-church** [comment]
Done so closing

**Comment by arun3jyothi** [comment]
I cant find import/Replace option in composer playground.  please  help

**Comment by caroline-church** [comment]
@arun3jyothi you can only now import a bna when you deploy a business network. It is no longer possible to import a bna once a business network is deployed. However you could import the model files, scripts and acl rules separatelyif you wanted

**Comment by arun3jyothi** [comment]
Hi Caroline,


Thanks for the reply.

**Comment by dhrubesh** [comment]
![image](https://user-images.githubusercontent.com/11453045/40361213-30355ea4-5de6-11e8-8313-df5ba481b4c0.png)
I'm unable to find a way to import my bna file. The import option isn't visible for me. Can anyone help me here?

**Comment by jt-nti** [comment]
@dhrubesh it would be better to ask this kind of question on Rocket.Chat rather than adding a comment to a closed issue. To create a new business network based on a bna file in the latest playground, you'll need to click on "Deploy a new business network" on the business network screen- you can upload your bna in section 2 of the deploy screen that opens.
