### ISSUE TITLE
Npm install fails, getting started project 

### ISSUE THREAD

**Issue by bonen** [fabric-composer/fabric-composer#172]
Very cool project!!
Can't get the getting-started-sample-application working though.

Some output:

Tell the author that this fails on your system:
npm ERR!     composer archive create -m digitalproperty-network --archiveFile digitalPropertyNetwork.bna && composer network deploy --archiveFile digitalPropertyNetwork.bna  --enrollId WebAppAdmin --enrollSecret DJY27pEnl16d && composer network list -n digitalproperty-network --enrollId WebAppAdmin --enrollSecret DJY27pEnl16d

Error: Failed to load connector module "composer-connector-hlf" for connection profile "defaultProfile"
Command failed.

npm ERR! node v7.4.0
npm ERR! npm  v4.3.0

**Comment by sstone1** [comment]
Hi @bonen, I think you will find that `npm install` will have failed with errors from `node-gyp` when it is building some native C++ modules. These errors occur because you are running with node v7.x and some of the modules that we depend on do not compile with node v7.x yet.

In order to resolve the problem you need to:
1. Downgrade to node v4.x or v6.x and confirm with `node -v`.
2. Remove any old npm modules by deleting the module folder `rm -rf node_modules`. You may also need to uninstall the CLI by running `sudo npm uninstall -g composer-cli`.
3. Run all install steps again in our documentation that use `npm install`.

**Comment by bonen** [comment]
Thanks a lot @sstone1 !
Now running 6.9.5 and it works like a charm.
