### ISSUE TITLE
sudo required in prerequisites?

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#225]
on the following page https://fabric-composer.github.io/tasks/prerequisites.html  under  "Automatic Installation"
the instructions state that command completes the installation process is
      ./scripts/prereqs-ubuntu.sh docker

Should this command be as follows instead of the way it is written ?
    sudo     ./scripts/prereqs-ubuntu.sh docker

Else I get a permission denied error

**Comment by davidkel** [comment]
Through the first run of the script sudo is used to ensure the installation works, but on the 2nd run of the script when you specify the docker parameter sudo isn't used. I'll change the script for that section to use sudo so it is consistent with the rest of the script.

**Comment by mbwhite** [comment]
When we had issues with the Ubuntu 14:04; the issue was with the way this script pulls in the docker-compose code. It was using python/pip - when really all it needs to do is a curl. 

@Jakeeyturner did you modify the script to do this?

Also I didn't see any specific need to have the script run twice - the curl for docker-compose can be done at the end. Yes it's true you need to log out and log back in, but don't think is a requirement for pulling down docker-compose.

Would also suggesting that we addin a curl command for them to optionaly get the script directly
```
curl -O https://raw.githubusercontent.com/fabric-composer/sample-applications/master/packages/getting-started/scripts/prereqs-ubuntu.sh
chmod u+x prereqs-ubuntu.sh
```

**Comment by davidkel** [comment]
ok, the current script is fixed for now to match the docs. I will look at doing improvements to the script and updating the docs to match changes

**Comment by caroline-church** [comment]
close and we can create new issues for any improvments
