### ISSUE TITLE
Archive that includes ACL file is drastically slower to deploy

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#230]
The attached archive (including ACL file) is taking ± 5 minutes to deploy. If you remove the ACL file the deploy takes 30 seconds.

[medrecs.zip](https://github.com/fabric-composer/fabric-composer/files/793315/medrecs.zip)

**Comment by pastadin** [comment]
I think the issue is specifically related to using self-executing functions for a rule's Predicate.

If you edit rule `PR1` in `permissions.acl`, the following (included in the file @dselman attached) takes about 3 mins to deploy.

`( (thePatient.externalDoctors.some(function(doctor){return doctor.getIdentifier() === currentDoctor.getIdentifier();}))() )`

By making it a statement instead of self-executing it cuts the deployment time down to 50 seconds:

`(thePatient.externalDoctors.some(function(doctor){return doctor.getIdentifier() === currentDoctor.getIdentifier();}))`

I've included a version of the `.bna`

 with the new rule.
[medrecs.bna.zip](https://github.com/fabric-composer/fabric-composer/files/793429/medrecs.bna.zip)

**Comment by pastadin** [comment]
If you further edit rule `PA2` in `permissions.acl` to have the following as the predicate instead of `(true)` (It's current value) then the deploy time slows again to 2 minutes:

`(currentPatient.records.some(function(record){if (record.type === 'VACCINATION'){return record.vaccine.getIdentifier() === theVaccine.getIdentifier();}return false;}))`

I've included another zip containing a bna with this modification:

[medrecs.bna.zip](https://github.com/fabric-composer/fabric-composer/files/793455/medrecs.bna.zip)

**Comment by pastadin** [comment]
Further bug, you can't do updates with the BNA either - even if you remove the ACL it times out each time.

**Comment by sstone1** [comment]
@pastadin stop spamming everyone with this one 😛

So there is no execution of ACL rules on a deploy, this is purely a parse/validation problem.

I added some tracing for this problem last week and it seems that the problem is occurring in the ACL rule parser. That code is machine generated code, generated by pegjs from a grammar file. I believe the JavaScript parsing portion of this code was taken from pegjs (@dselman can confirm).

The question we need to answer is: is the ACL rule _relatively_ slow (it is unlikely to be slow enough to be obvious to a human without adding timing information) to parse on Node.js and the problem is actually in the parser, with Otto performing much worse due to it being an interpreter? Or is the problem Otto specific, which will be difficult to track down and fix.

@Jakeeyturner since @pastadin name dropped you earlier, please can you try tracing the time it takes to parse the ACL rule. The code is in `aclfile.js`. I suggest that you write some kind of test driver script that just calls `new AclFile` in a loop to measure the time it takes to parse various ACL rules (including this one). You could speak to @mbwhite or @davidkel who I think are good candidates for having been involved with doing some performance analysis work at some point 😉

**Comment by dselman** [comment]
If necessary it would be easy to change the grammar to be `(` STRING `)`

**Comment by caroline-church** [comment]
@pastadin Can you please retest this on the latest ACL syntax please? and reopen if its still a problem
