### ISSUE TITLE
As a user i can add a file to my business network in composer playground

### ISSUE THREAD

**Issue by caroline-church** [fabric-composer/fabric-composer#298]
On the define page be able to click `add a file` and then be able to add a blank file or be able to drag and drop a file from your filesystem.

See page 12, 18  (need design to add what happens after you have dropped the file)

**Comment by winslet** [comment]
**Flow:**

_1. User selects "Add a file" from the left hand navigation_

![fabric composer playground define 2 copy 58](https://cloud.githubusercontent.com/assets/13980028/23547350/c8fd998a-fffa-11e6-8fa7-8fbe77a30f85.png)

_2. User can either select a file to be added or drag a file in, this is the drag n drop:_

![fabric composer playground define 2 copy 59](https://cloud.githubusercontent.com/assets/13980028/23547587/a4aeade8-fffb-11e6-98bf-c95761a8fff5.png)

**Note!** this drag and drop interaction/component has already been worked on for the upload of the business network and should be reusable.

_3. User is able to see information about the CTO file and choose whether to import it or remove it_

![fabric composer playground define 2 copy 84](https://cloud.githubusercontent.com/assets/13980028/23548186/29034318-fffe-11e6-9e1c-adbad288000e.png)

**Question** - What information (if any) can we pull out of the CTO/JS file in order to help our users decide whether they are the correct files before adding them?

**Assets:**
[CTO_JS_Upload_Assets.zip](https://github.com/fabric-composer/fabric-composer/files/816535/CTO_JS_Upload_Assets.zip)

**Marketch:**
[CTO_JS_Upload_Marketch.zip](https://github.com/fabric-composer/fabric-composer/files/816539/CTO_JS_Upload_Marketch.zip)

**Comment by 14gracel** [comment]
We can basically get all of the information about each file. In the model files we can get everything about the declarations, and in the scripts we can get all of the function declarations

**Comment by winslet** [comment]
@14gracel thats great news, to someone who is not technical (me) - could you explain what those things are and what you feel would be of most value to preview?

**Comment by 14gracel** [comment]
@winslet Honestly I think the current data that is shown on the mockups, the number of assets, transactions and participants is fine. I dont think there is any value showing anything more than that

**Comment by winslet** [comment]
@14gracel great, lets roll with that for the time being. Cheers 👍
