### ISSUE TITLE
As a user I should be able to easily set up a REST API server using Loopback

### ISSUE THREAD

**Issue by sstone1** [fabric-composer/fabric-composer#42]
**Background**

The current Loopback support requires that the user creates a Loopback application using the `lb` command and then adds in a Fabric Composer boot script. The boot script configures Loopback with the Fabric Composer connector and connection settings, and then drives the Loopback discovery APIs to inspect the business network definition stored on the blockchain.

We need to improve this experience so that a Fabric Composer user looking to get started with business network or application development, who doesn't necessarily care about Loopback when trying to expose their business network via a REST API, or doesn't need the configuration options that a Loopback application provides, can easily set up a REST API.

We should be clear that for any kind of production implementation of the REST API, you will need a Loopback application and you need to understand the Loopback framework. Production users will want full control over configuring HTTPS, authentication (LDAP, SAML, OAuth?), etc and wrapping all of the relevant Loopback configuration in Composer specific configuration is a waste of effort.

**Proposal**

I have two suggestions for improving this experience:

1. A Yeoman generator that drives the Loopback application generator, and adds the boot script. The configuration would look something like:

```
$ yo composer:rest
Welcome to the REST API server generator for Fabric Composer
? Your app name: test-app
? Short description: Test Composer project
? Author name: Simon Stone
? Author email: SSTONE1@uk.ibm.com
? What is the Business Network Identifier?: org.acme.biznet
? What is the Connection Profile to use? hlfabric1
? Enrollment id: sstone1
? Enrollment Secret: DJY27pEnl16d
...
$ cd test-app
$ npm start
```

2. We generate a Loopback application and wrap the startup and configuration of that Loopback application into a simple CLI interface. "Our" Loopback application can then be published as an NPM module which can be easily installed by our users. Something that provides an experience similar to:

```
$ npm install composer-rest-server
...
$ composer-rest-server -P 8919 -p hlfabric1 -n org.acme.biznet -i sstone1 -s zFyTqkFWQJfw
Loopback server now running on port 8919!
```

This is nicer than 1) as the user does not have to maintain a generated Loopback application.

**Comment by dselman** [comment]
I like the second option because, as you say, it is an application that we maintain and can improve. 

I would also like to challenge the team to think about how we can expose the REST API (dynamically generated) inside the Composer web UI. I want to be able to edit a model and instantly see the updated REST API, and test using Postman. No servers, no configuration!

**Comment by samjsmith** [comment]
I agree and also prefer the second option because I think that with the first option, users may well not know the details of connection profiles, enrollment ids/secrets when they generate the application and once they've run the generation step, would have to go and edit config files. 

With the separate application approach, at least we could provide a nicer experience for users going through that process.

**Comment by samjsmith** [comment]
Closing this one as it has been implemented now and errors/problems can be reported in new issues.

**Comment by dselman** [comment]
Can you please ensure that tests are in place and this is documented under tasks:
https://fabric-composer.github.io/tasks/

**Comment by samjsmith** [comment]
- [ ] licence check
- [ ] dev dependencies in package.json
- [ ] tests
