### ISSUE TITLE
As an offering manager I have access to Net Promoter Score statistics

### ISSUE THREAD

**Issue by harrika1982** [fabric-composer/fabric-composer#453]
## Context
We need a way to collect feedback from users and stats on user engagement so that we can understand how willing users are to recommend Fabric Composer to a friend/colleague.

## Expected Behavior
After using Fabric Composer for some time, a developer should be prompted with the question of whether they are likely to recommend Fabric Composer to a friend. 

## Actual Behavior
Currently no questions

**Comment by EdMoffatt** [comment]
Adding in some detail on what we're looking for here based on conversation with Kathryn yesterday...

Visitors to fabric-composer.org can take 2 routes to get started:

1. Jump straight in to the web Playground, and learn what it is and how it works in a hands-on way
2. Install the local version of the Playground locally (or the CLI tools) without ever experiencing the web Playground

We'd like to make sure that in either case we have the opportunity to request a feedback score from the user.  IBM standard for gathering this is Net Promoter Score (NPS), so for ease of comparison to other offerings we'll use this too.

So, what we need is...

1. A user of the web Playground is asked to provide a NPS.  This needs to not happen immediately, but after they've been using the playground for a while.  It should also be a "push" interaction i.e. we want to prompt the user rather than have something in the UI for them to choose to interact with if they want to give us a score.  Therefore, we need to figure out something to trigger the prompt being displayed.  Kathryn and I thought "when a model is deployed" would be a good trigger, but speaking to Dan that doesn't work as neatly as we'd thought, since importing a sample network also triggers an update, and we're going to be asking users to do that as one of the very first steps in the first tutorial, so it's too early!
So, need to figure out the trigger, and then how we will work it in.
2. A user who never goes to the web Playground is a separate consideration.  Initial suggestion is that we could have a trigger on the website, whereby when somebody visits the "Community" page, we prompt for NPS.  It seems likely that someone who's looking for the Community info has already had a bit of Fabric Composer experience, so it seems a sensible time to prompt.

All this of course needs further discussion, just capturing the state of play here for now!

**Comment by dselman** [comment]
I think it is also worth highlighting that this is COMMUNITY information, so whatever mechanism we use will need to be pluggable so that vendors that deploy Playground in their own environments can switch this off or use alternate schemes.

**Comment by EdMoffatt** [comment]
Current status:

Link to a Google Sheets survey being added to the Community page of the docs site with the next build.

UI prompt is in the latest unstable build, but needs some fixes:

- [ ] Wording of request should be "How likely are you to recommend Fabric Composer to a friend or colleague?"
- [ ] Scale should be from "Not at all" to "Extremely" (optionally with "likely" on the end of both or neither of those).  This matches the wording used for all Bluemix services, and we wouldn't want to make our stats un-comparable to other services by using a different scale!

**Comment by dselman** [comment]
This is an interesting approach, in that data is stored by Google Analytics, and we have complete control over the UI:
https://medium.com/@marco.herzog/build-your-own-nps-net-promoter-score-tool-using-analytics-js-cc2fcee36346#.vxgps2w9i

**Comment by EdMoffatt** [comment]
Ok, we're done on this one for now, so closing the issue :)  What we picked was...

1. Link to give feedback via a Google Sheets form on the Community page of the docs site
2. Slide-in request for feedback after the user Updates their Business Network Definition in the web Playground

These will be live with today's build.
