### ISSUE TITLE
As a user I can manually run an initialization function within a business network definition from Composer Playground

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#46]
A business network definition should be able to contain a JS script that can be launched by the Composer Playground user. The script can initialize demo assets, transaction and participants.

**Comment by EdMoffatt** [comment]
See pages 17-19 in the latest low-fi mockup: https://xd.adobe.com/view/a2b13e4c-a2c7-4d56-95bc-db506cb58460/

Setup script is not shown in the "Define" tab, but if it exists then we include the button to run it in the "Test" tab.
Question around how this works (that will effect the final design):
- Can you run the setup script multiple times?  i.e. if we create a car via the setup script, will it be a specific one so that running it again would get you an error, or should we randomise, so that running again will just get you more of them?

**Comment by samjsmith** [comment]
Concensus in the room is that we need a few more details on this. What's the Function annotation that will be used to identify the func?

**Comment by dselman** [comment]
Another approach to accomplish this would be a user defined `Setup` transaction type. The user can then define a TP function that runs when `Setup` is submitted. This removes the need for any new runtime functionality or UI. The README.md for the network can describe that an instance of `Setup` should be submitted first.

**Comment by caroline-church** [comment]
samples use setup demo transaction
