### ISSUE TITLE
Cannot create an asset in Playground

### ISSUE THREAD

**Issue by dselman** [fabric-composer/fabric-composer#580]
## Context
Using a relatively complex model it appears that the JSON generation fails for a modeled type `Contract`. 

## Expected Behavior
Should be able to create an instance of a `Contract`.

## Actual Behavior
JSON editor appears empty.

<img width="719" alt="screen shot 2017-03-29 at 05 59 39" src="https://cloud.githubusercontent.com/assets/623108/24439234/edc25450-1444-11e7-9654-edecd3ce8454.png">

## Steps to Reproduce

1. Go to http://composer-playground-unstable.mybluemix.net
2. Import the BNA file (remove the .zip from the name)
[contract-network@0.0.5.bna.zip](https://github.com/fabric-composer/fabric-composer/files/877854/contract-network.0.0.5.bna.zip)
3. Switch to the Test tab
4. Try to create an instance of `Contract`

## Existing issues

- [x] [StackOverflow issues](http://stackoverflow.com/tags/fabric-composer)
- [x] [GitHub Issues](https://github.com/fabric-composer/fabric-composer/issues)
- [x] [Rocket Chat history](https://chat.hyperledger.org/channel/fabric-composer)

## Your Environment

* Version used: 0.5.6 (unstable)
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by samjsmith** [comment]
Looks to me like this is a problem in the composer-common Factory class. The UI makes a call to the factory to the newResource method with what looks like the right parms. From what I can tell, this then reads the model and gets the 'Contract' definition. 

I'm not familiar with this code but from the simple console.logs I've added, it looks like it tries to then create a new 'ParameterValue' instance which is declared as abstract which triggers the check here: https://github.com/fabric-composer/fabric-composer/blob/master/packages/composer-common/lib/factory.js#L123-L125

I'm not sure why that error is ignored/not reported by the UI though.

**Comment by samjsmith** [comment]
![image](https://cloud.githubusercontent.com/assets/16335033/24446712/67743b58-1466-11e7-9dab-0e2ae19a2d37.png)

**Comment by dselman** [comment]
I think you are on the right lines here -- the model has a collection of an abstract type, so we need to go looking for types that extend the abstract type and that are non-abstract. Once we've built that collection we can probably pick one at random to instantiate and randomly populate.

The `ModelUtils.isAssignableTo` method should be useful to check whether a class declaration (retrieved from the Introspector) can be stored in a property.

**Comment by vipin1989gupta** [comment]
I have two transactions GoodsMovement and Payment.  GoodsMovement will track delivery of Goods and Payment transaction will check for payments if goods are delivered.I'm working on below code:

    /**
 * New model file
 */

namespace org.acme.paysystem

enum PaymentStatus{
o PARTIALLY_PAID
o TOTAL_AMOUNT_PAID
o NOT_PAID
}

enum DeliveryStatus{
o DELIVERED
o IN_TRANSIT
}

asset Goods identified by billNo{
  o String billNo
  o Double billAmount
  o DateTime billDate
  o DeliveryStatus deliveryStatus
  o PaymentStatus paymentStatus default = 'NOT_PAID'
}

concept Address{
o String Country optional
o String City optional
o String Street optional
o String Zip optional
}

abstract participant user identified by email{
  o String email
  o String fname
  o String lname
  o Address address
}

participant Retailer extends user {
o String shopNo
o Double amountDue
o Double accountBalance
}

participant Distributor extends user{
o String PAN
o Double bankBalance
}

transaction Payment{
  --> Goods goods
  --> Retailer retailer
  --> Distributor distributor
  o PaymentStatus paymentStatus
}

transaction GoodsMovement {
  --> Goods goods
  o DeliveryStatus deliveryStatus
}

I haven't mentioned GoodsMovement transaction here since it's working as expected.

/**
* @param {org.acme.paysystem.Payment} Payment
* @transaction
*/
function Payment(Payment){
        var paymentRecievedFlag = 0;
        var amountRecieved = 0;
                if(GoodsMovement == 'IN_TRANSIT')
                    {
                         console.log("Goods are IN_TRANSIT");
                    }
          else
          {
            if ((Payment.retailer.accountBalance - Payment.goods.billAmount) > 0 ){
               Payment.retailer.accountbalance -= Payment.goods.billAmount;
               Payment.distributor.bankBalance += Payment.goods.billAmount;

              Payment.paymentStatus = 'TOTAL_AMOUNT_PAID';
              //Payment.goods.paymentStatus = 'TOTAL_AMOUNT_PAID';
          }

            else{
                  Payment.retailer.amountDue = Payment.goods.billAmount - Payment.retailer.accountBalance;
                  Payment.distributor.bankBalance += Payment.retailer.accountBalance;
                  Payment.paymentStatus = PARTIALLY_PAID;
            }}


          return getParticipantRegistry('org.acme.paysystem.Distributor')
               .then(function(distributorRegistry){
                  return distributorRegistry.update(Payment.distributer);
          })
               .then(function(){
                  return getParticipantRegistry('org.acme.paysystem.Retailer');
          })
               .then(function(retailerRegistry){
                  return retailerRegistry.update(Payment.retailer);
          })
                 .then(function(){
                       return getAssetRegistry('org.acme.paysystem.Goods');
          })
                 .then(function(goodsRegistry){
                        return goodsRegistry.update(Payment.goods);
          });       
}
I have checked properly and search through Internet too but I'm not able to figure it out what's the problem with my code. Thanks if anyone could help me out with code
